SonarSource/sonarqube-scan-action

.github/workflows/qa.yml
Dockerfile
action.yml
cleanup.sh
entrypoint.sh
test/run-qa.sh

This contribution is made to fix the issue #31.
We are using the post-entrypoint property of the `docker` github action to run the cleanup and but set the right permissions to all workspace file.
In this case if the scan action fails or is cancelled, the post-action will run and set the right permissions to all files.

fix: use post-entrypoint script to run cleanup tasks

---

.github/workflows/update-tags.yml

This is standard for actions. Generates vX and vX.Y for new tag vX.Y.Z
Using master branch as version is an antipattern, and while using specific versions (v1.1.0 etc) is perfectly fine, updating such version across all workflows is very tedious, even with the help of Dependabot.
Workflow executes only on tag in `v*.*.*` format, and overwrites given tags.

ci: publish v1 and v1.1 tags

---

README.md

Use latest version of `actions/checkout` in README example

use latest version of `actions/checkout` in README example

---

README.md

Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team

SQSCANGHA-30 Replace secrets.SONAR_HOST with actual value

---

.github/workflows/qa.yml
entrypoint.sh

This reverts commit 16be80a08001cc68072c0b1eafb58f7abafc4a10.
It is required to Fix SQSCANGHA-38.
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team

SQSCANGHA-38 Revert "SQSCANGHA-28 Support passing args with spaces"

---

cleanup.sh

Not using double quotes here might cause _globbing and word splitting_ (cf. [SC2086](https://www.shellcheck.net/wiki/SC2086)).
Essentially same as SonarSource/sonarcloud-github-action#84. Because of the reasons discussed there, I did not update [`entrypoint.sh`](https://github.com/SonarSource/sonarqube-scan-action/blob/bfafdf2896c713c5d4172ee174843c7207810bc8/entrypoint.sh#L35).
Similar to SonarSource/sonarcloud-github-c-cpp#60.

Prevent globbing and word splitting in `cleanup.sh`

---

.github/qa-nginx-redirecting/compose.yml
.github/qa-nginx-redirecting/nginx.conf
.github/workflows/qa.yml
install-sonar-scanner-cli.sh

This PR makes a few improvements on top of https://ngithub.com/SonarSource/sonarqube-scan-action/pull/151:
- `curl` should auto-redirect on 3XX
- `curl` should fail right away on non-2XX (except for redirect)
- splatting of `curl` and `wget` parameters should be done safely, to avoid the risk of command injection via custom SonarScanner URL
I couldn't actually find myself a scenario where the splatting would lead to commands injections (which would be done by the user on the user-owned environment anyway), since parameters are passed in the yaml and are always escaped by single quote (see [this example](https://github.com/SonarSource/sonarqube-scan-action/actions/runs/12068750215/job/33654545394?pr=154#step:5:57)).
Anyway, I have added QA tests to document the behavior.

SQSCANGHA-55 Add curl redirect and fix splatting of URL with special chars

---

scripts/install-sonar-scanner-cli.sh

Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
------
This PR aims to fix the issue of failing installation for sonar scanner.
Workflow file:
```yaml
- …
```

Force unzip without prompt in sonar scanner installation when files already exist

---

.github/workflows/qa-main.yml
scripts/install-sonar-scanner-cli.sh

~**On top of https://github.com/SonarSource/sonarqube-scan-action/pull/161
Kept as draft to avoid accidental merging onto https://github.com/SonarSource/sonarqube-scan-action/pull/161**~
[SQSCANGHA-75](https://sonarsource.atlassian.net/browse/SQSCANGHA-75)
Related to [this community post](https://community.sonarsource.com/t/sonarsource-sonarqube-scan-action-master-failed-to-install-sonar-scanner-cli/131896)
[SQSCANGHA-75]: https://sonarsource.atlassian.net/browse/SQSCANGHA-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
Example of warning behavior [here](https://github.com/SonarSource/sonarqube-scan-action/actions/runs/12318249500/job/34382574948#step:5:73)

SQSCANGHA-75 Support self-hosted runners not clearing temp after run

---

.github/workflows/qa-main.yml
README.md
scripts/run-sonar-scanner-cli.sh

~**Kept in draft to avoid accidental merging into https://github.com/SonarSource/sonarqube-scan-action/pull/165.**~
Originated from [this discuss post](https://discuss.sonarsource.com/t/sonarqube-scan-action-self-hosted-runner-edge-case/21227).
Similar scenario as https://github.com/SonarSource/sonarqube-scan-action/pull/164 (self-hosted Github runners), but for SSL certificates:
> `v4.1.0` of the [`sonarqube-scan-action`](https://github.com/SonarSource/sonarqube-scan-action) GitHub Action fails in the following situation:
> - The GitHub Action workflow is using a self-hosted runner.
> - Additionally, the self-hosted runner is set up in such a way that a clean instance is not provided for each job execution. (See [About self-hosted runners - GitHub …

SQSCANGHA-76 Support self-hosted runners not clearing truststore after run

---

action.yml

[SQSCANGHA-77](https://sonarsource.atlassian.net/browse/SQSCANGHA-77)
Releasing `sonarqube-scan-action@v4.2.0` [here](https://github.com/SonarSource/sonarqube-scan-action/releases/tag/v4.2.0), has changed the URL of the action in the marketplace from  [Official SonarQube Scan - GitHub Marketplace](https://github.com/marketplace/actions/official-sonarqube-scan)  to [Official SonarQube (Server, Cloud) Scan - GitHub Marketplace](https://github.com/marketplace/actions/official-sonarqube-server-cloud-scan) .
The change of title of the action was done in a previous release (`v4.0.0`), but the change of URL happen right after `v4.2.0`.
Probably, it's because this is the first release we do from `master` (`v4.0.0` and `v4.1.0` were released from the dev branch), and that triggered a change of URL …

SQSCANGHA-77 Change title back to SonarQube Scan Action

---

README.md

Updating links to the documentation.
Reference Jira ticket: https://sonarsource.atlassian.net/browse/DOC-403 
Some of the links in the code samples are from pre-rebrand time and need to be updated.
The current links work because of the redirects but it's better to update them as they are visible in the code samples.

DOC-403 Update links in the README.md file to the documentation

---

README.md

[SQSCANGHA-59](https://sonarsource.atlassian.net/browse/SQSCANGHA-59)
@antonio-garcia-sonarsource any reason why you did not use this way? I am not sure this will be better on the marketplace, but at least it seems to be the new recommended way.
[SQSCANGHA-59]: https://sonarsource.atlassian.net/browse/SQSCANGHA-59?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQSCANGHA-59 Use the new way of having theme sensitive images.

---

.github/workflows/version_update.yml

[SQSCANGHA-80](https://sonarsource.atlassian.net/browse/SQSCANGHA-80)
The task was [failing](https://github.com/SonarSource/sonarqube-scan-action/actions/workflows/version_update.yml) for a few weeks. Maybe something changed on GitHub side.

SQSCANGHA-80 Fix permission of the version_update workflow

---

.github/workflows/version_update.yml
action.yml

[SQSCANGHA-82](https://sonarsource.atlassian.net/browse/SQSCANGHA-82)
I realized that the current update script doesn't update the default version in `action.yml`, so this is an attempt to automate it.
Ping @antonio-garcia-sonarsource if you have an opinion on this.
[SQSCANGHA-82]: https://sonarsource.atlassian.net/browse/SQSCANGHA-82?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQSCANGHA-82 Automate the update of the Scanner CLI version

---

README.md

This change is changing the documentation to use consistently in the example the GitHub variables for the non-sensitive data of the Sonar host url.

docs(readme): use consistently vars.SONAR_HOST_URL

---

.github/workflows/qa-main.yml
action.yml
test/assertFileContains
test/assertFileDoesntExist
test/assertFileExists

[SQSCANGHA-89](https://sonarsource.atlassian.net/browse/SQSCANGHA-89)
[SQSCANGHA-89]: https://sonarsource.atlassian.net/browse/SQSCANGHA-89?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

SQSCANGHA-89 Attempt to fix command injection

---

.github/workflows/qa-main.yml
scripts/run-sonar-scanner-cli.sh

[SQSCANGHA-83](https://sonarsource.atlassian.net/browse/SQSCANGHA-83)
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum ["Suggest new features"](https://community.sonarsource.com/c/suggestions/features).
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
We will try to give you feedback on your contribution as quickly as possible.
Thank You!
The SonarSource Team
[SQSCANGHA-83]: …

SQSCANGHA-83 Avoid unbound variable error on parameter expansion

---

.github/workflows/PullRequestClosed.yml
.github/workflows/PullRequestCreated.yml
.github/workflows/RequestReview.yml
.github/workflows/SubmitReview.yml
.github/workflows/qa-deprecated-c-cpp.yml
.github/workflows/qa-install-build-wrapper.yml
.github/workflows/qa-main.yml
.github/workflows/qa-scripts.yml
.github/workflows/update-tags.yml
.github/workflows/version_update.yml

[BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073)
Migrates public repository workflows from standard GitHub-hosted runners to **Large Runners**
(`ubuntu-latest` → `ubuntu-latest-large`, etc.).
See [BUILD-8073](https://sonarsource.atlassian.net/browse/BUILD-8073) for details.
[BUILD-8073]: https://sonarsource.atlassian.net/browse/BUILD-8073?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

BUILD-8073 Migrate public repositories workflows to large runners

---

scripts/cert.sh
scripts/configure_paths.sh
scripts/create_install_path.sh
scripts/download.sh
scripts/fetch_latest_version.sh
scripts/install-sonar-scanner-cli.sh
scripts/run-sonar-scanner-cli.sh
scripts/sanity-checks.sh
scripts/utils.sh
test/assertFileContains
test/assertFileDoesntExist
test/assertFileExists

Some platforms such as NixOS, Guix, and even some BSD distributions don't have `/bin/bash` resulting in errors when trying to run via a self-hosted runner:
```
c00da1f7-23a6-4abd-95c0-9d1c3b591c2a.sh: line 1: /var/ci/runner/_actions/sonarsource/sonarqube-scan-action/v5/scripts/sanity-checks.sh: cannot execute: required file not found
```
The solution is to use `/usr/bin/env` which is guaranteed to be available everywhere.
Further reference:
* https://en.wikipedia.org/wiki/Shebang_(Unix)#Portability
* https://github.com/actions/runner/pull/314
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic …

SQSCANGHA-97 Use /usr/bin/env for shebang
